#!/usr/bin/env node
"use strict";

const crypto = require("node:crypto");
const fs = require("node:fs");
const http = require("node:http");
const os = require("node:os");
const path = require("node:path");
const process = require("node:process");
const {
  getBlockedPageError
} = require("../Scraper/background/run-lifecycle-helpers.js");

let cloakbrowser;
const RUNNER_EVENT_PREFIX = "RUNNER_EVENT ";
const RUN_SOURCE = {
  portalServer: "PORTAL_SERVER"
};
const DEFAULT_START_URL_WARMUP_TIMEOUT_MS = 45_000;
const DEFAULT_START_URL_WARMUP_POLL_INTERVAL_MS = 750;
const DEFAULT_START_URL_WARMUP_RELOAD_AFTER_MS = 12_000;
const PORTAL_AUTH_TOKEN_TTL_MS = 8 * 60 * 60 * 1000;
const PORTAL_AUTH_RENEWAL_LEAD_MS = 15 * 60 * 1000;
const PORTAL_AUTH_RENEWAL_INTERVAL_MS = PORTAL_AUTH_TOKEN_TTL_MS - PORTAL_AUTH_RENEWAL_LEAD_MS;
const PORTAL_AUTH_RENEWAL_RETRY_MS = 60 * 1000;
const SIGNAL_EXIT_CODES = {
  SIGINT: 130,
  SIGTERM: 143
};

// Locale + timezone fingerprint identity. Cloakbrowser applies these via
// patched-Chromium binary flags (--lang, --fingerprint-locale,
// --fingerprint-timezone) instead of CDP context emulation, so the
// override is invisible to detection scripts. UA / Sec-CH-UA / viewport /
// navigator surface / WebGL / canvas / audio are auto-generated by the
// binary from a per-launch seed (see cloakbrowser's getDefaultStealthArgs).
//
// These defaults are used when no explicit override is passed and
// --auto-stealth-geo is off (or no proxy is configured). With
// --auto-stealth-geo, cloakbrowser's geoip:true option resolves the
// proxy's exit IP and fills in any missing locale/timezone from an
// offline GeoLite2 database; explicit overrides still win.
const STEALTH_LOCALE = "en-US";
const STEALTH_TIMEZONE = "Europe/Vilnius";

// Egress probe + IP-repetition guard. Stored in the persistent profile so
// the history survives across runs of the same robot — the rotating
// residential proxy provider has a known repetition risk on refresh, so
// we want to detect when a "rotated" proxy actually returns the same IP
// we just got blocked on.
const EGRESS_HISTORY_FILE = ".scraper-egress-history.json";
const EGRESS_HISTORY_RING_SIZE = 10;
const EGRESS_PROBE_TIMEOUT_MS = 8_000;
const EGRESS_PROBE_HOST = "ip-api.com";
const EGRESS_PROBE_PATH = "/json?fields=status,query";

// Operational launch args only. Stealth-related flags
// (--disable-blink-features=AutomationControlled, fingerprint spoofs,
// --enable-automation removal, etc.) are applied by cloakbrowser itself.
// WebRTC IP-leak prevention is the exception — cloakbrowser does not
// configure it, so we set the policy here. Without this Chromium can
// still expose the host's real IP via STUN/UDP even when all HTTP
// traffic flows through the configured proxy.
const STEALTH_LAUNCH_ARGS = [
  "--no-first-run",
  "--no-default-browser-check",
  "--disable-infobars",
  "--disable-dev-shm-usage",
  "--disable-background-timer-throttling",
  "--disable-backgrounding-occluded-windows",
  "--disable-renderer-backgrounding",
  "--force-webrtc-ip-handling-policy=disable_non_proxied_udp",
  "--enforce-webrtc-ip-permission-check"
];
const CONTROL_PLANE_PROXY_BYPASS_HOSTS = [
  "127.0.0.1",
  "localhost",
  "::1"
];

// Aggressive resource blocking. Runs at the Playwright route() layer for
// every page in the persistent context, so it only ever applies to runs
// driven by this runner (which is server-only — local runs use the
// extension directly in the user's Chrome). Goal: cut bandwidth on the
// residential proxy by dropping anything that isn't required to render
// the product DOM or pass anti-bot checks.
const BLOCKED_RESOURCE_TYPES = new Set([
  "image",
  "media",
  "font",
  "stylesheet"
]);

// Substrings matched against the request hostname (lower-cased). Any hit
// aborts the request. Keep this list to vendors that are pure analytics,
// advertising, session-replay, or tag-management — never anti-bot
// challenge providers, payment widgets, or anything a site might depend
// on for hydration.
const BLOCKED_HOST_PATTERNS = [
  "google-analytics.com",
  "googletagmanager.com",
  "googletagservices.com",
  "googlesyndication.com",
  "doubleclick.net",
  "adservice.google.",
  "g.doubleclick.net",
  "connect.facebook.net",
  "facebook.net",
  "analytics.tiktok.com",
  "ads.tiktok.com",
  "static.ads-twitter.com",
  "ads-twitter.com",
  "snap.licdn.com",
  "px.ads.linkedin.com",
  "ct.pinterest.com",
  "bat.bing.com",
  "clarity.ms",
  "hotjar.com",
  "hotjar.io",
  "mixpanel.com",
  "cdn.segment.com",
  "api.segment.io",
  "amplitude.com",
  "fullstory.com",
  "logrocket.com",
  "newrelic.com",
  "nr-data.net",
  "branch.io",
  "omtrdc.net",
  "demdex.net",
  "everesttech.net",
  "2o7.net",
  "adobedtm.com",
  "criteo.com",
  "criteo.net",
  "amazon-adsystem.com",
  "quantserve.com",
  "scorecardresearch.com",
  "taboola.com",
  "outbrain.com",
  "chartbeat.com",
  "optimizely.com",
  "yandex.ru/metrika",
  "mc.yandex.ru"
];

// Page-context schemes that must never be intercepted: the extension's
// internal pages, Chromium UI, and devtools. Blocking here breaks the
// bridge page and any chrome:// settings the runner touches.
const RESOURCE_BLOCKER_SCHEME_ALLOWLIST = [
  "chrome-extension:",
  "chrome:",
  "devtools:",
  "about:",
  "file:",
  "data:"
];

async function loadCloakBrowser() {
  if (cloakbrowser) {
    return cloakbrowser;
  }

  try {
    cloakbrowser = await import("cloakbrowser");
    return cloakbrowser;
  } catch (error) {
    console.error("The runner needs the \"cloakbrowser\" package.");  // eslint-disable-line no-console
    console.error("Install it with: npm install --prefix runner");  // eslint-disable-line no-console
    throw error;
  }
}

function parseArgs(argv) {
  const options = {};

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (!arg.startsWith("--")) {
      continue;
    }

    const key = arg.slice(2);
    if (key === "headless") {
      options.headless = true;
      continue;
    }

    if (key === "headed" || key === "no-headless") {
      options.headless = false;
      continue;
    }

    if (key === "help") {
      options.help = true;
      continue;
    }

    const next = argv[index + 1];
    if (!next || next.startsWith("--")) {
      throw new Error(`Missing value for --${key}`);
    }

    options[key] = next;
    index += 1;
  }

  return options;
}

function resolveBoolean(value, fallback) {
  if (typeof value === "boolean") {
    return value;
  }

  if (typeof value !== "string" || !value.trim()) {
    return fallback;
  }

  const normalized = value.trim().toLowerCase();
  if (["1", "true", "yes", "on"].includes(normalized)) {
    return true;
  }

  if (["0", "false", "no", "off"].includes(normalized)) {
    return false;
  }

  return fallback;
}

function resolveInteger(value, fallback) {
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function normalizePortalOrigin(origin) {
  const fallback = "http://127.0.0.1:5077";
  if (typeof origin !== "string" || !origin.trim()) {
    return fallback;
  }

  const trimmed = origin.trim().replace(/\/+$/, "");

  try {
    const parsed = new URL(trimmed);
    if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
      return fallback;
    }

    parsed.hash = "";
    parsed.search = "";
    return parsed.toString().replace(/\/+$/, "");
  } catch (_error) {
    return fallback;
  }
}

function parseJsonOption(rawValue, label) {
  if (typeof rawValue !== "string" || !rawValue.trim()) {
    return null;
  }

  try {
    return JSON.parse(rawValue);
  } catch (error) {
    throw new Error(`Could not parse ${label} as JSON: ${error.message}`);
  }
}

function emitRunnerEvent(event, payload = {}) {
  console.log(`${RUNNER_EVENT_PREFIX}${JSON.stringify({ event, ...payload })}`);  // eslint-disable-line no-console
}

function createGracefulShutdownController({
  processImpl = process,
  logger = console
} = {}) {
  let context = null;
  let closePromise = null;
  let shutdownPromise = null;
  const handlers = new Map();

  async function closeContext(reason = "shutdown") {
    if (closePromise) {
      return closePromise;
    }

    const activeContext = context;
    context = null;

    if (!activeContext || typeof activeContext.close !== "function") {
      return false;
    }

    closePromise = Promise.resolve()
      .then(() => activeContext.close())
      .then(() => true)
      .catch((error) => {
        if (logger && typeof logger.error === "function") {
          logger.error(`Could not close Chromium context during ${reason}: ${error?.message || error}`);  // eslint-disable-line no-console
        }
        if (processImpl && !processImpl.exitCode) {
          processImpl.exitCode = 1;
        }
        return false;
      });

    return closePromise;
  }

  function requestShutdown(signal) {
    if (shutdownPromise) {
      return shutdownPromise;
    }

    const exitCode = SIGNAL_EXIT_CODES[signal] || 1;
    if (processImpl && !processImpl.exitCode) {
      processImpl.exitCode = exitCode;
    }

    if (logger && typeof logger.log === "function") {
      logger.log(`Received ${signal}; closing Chromium before exiting.`);  // eslint-disable-line no-console
    }

    shutdownPromise = closeContext(signal)
      .finally(() => {
        if (processImpl && typeof processImpl.exit === "function") {
          processImpl.exit(processImpl.exitCode || exitCode);
        }
      });

    return shutdownPromise;
  }

  function install() {
    if (!processImpl || typeof processImpl.once !== "function") {
      return;
    }

    ["SIGTERM", "SIGINT"].forEach((signal) => {
      if (handlers.has(signal)) {
        return;
      }

      const handler = () => {
        void requestShutdown(signal);
      };
      handlers.set(signal, handler);
      processImpl.once(signal, handler);
    });
  }

  function dispose() {
    if (!processImpl || typeof processImpl.off !== "function") {
      handlers.clear();
      return;
    }

    handlers.forEach((handler, signal) => {
      processImpl.off(signal, handler);
    });
    handlers.clear();
  }

  return {
    setContext(nextContext) {
      context = nextContext || null;
    },
    clearContext() {
      context = null;
    },
    closeContext,
    requestShutdown,
    install,
    dispose
  };
}

function usage() {
  return [
    "Usage:",
    "  npm start --prefix runner -- --portal-origin https://portal.example.com --email admin@example.com --password secret --robot-id robot_123",
    "",
    "Options:",
    "  --portal-origin      Portal base URL. Default: http://127.0.0.1:5077",
    "  --email              Portal login email",
    "  --password           Portal login password",
    "  --robot-id           Portal robot id to run",
    "  --step               Starting step name. Default: start",
    "  --start-url          Optional start URL override",
    "  --tag                Optional run tag override",
    "  --params-json        Optional JSON payload for step params",
    "  --config-json        Optional JSON payload for run config",
    "  --user-data-dir      Persistent Chromium profile directory",
    "  --extension-path     Extension source directory. Default: ../Scraper",
    "  --proxy-server       Upstream proxy, e.g. http://host:port or socks5://host:port",
    "  --proxy-username     Proxy auth username (optional)",
    "  --proxy-password     Proxy auth password (optional)",
    "  --proxy-bypass       Additional comma-separated proxy bypass list",
    "  --stealth-locale     Override BCP-47 locale (e.g. en-US, lt-LT). Default: en-US",
    "  --stealth-timezone   Override IANA timezone (e.g. Europe/Vilnius). Default: Europe/Vilnius",
    "  --auto-stealth-geo   Use cloakbrowser geoip:true to fill in locale/timezone from the proxy egress IP (default: false). Explicit overrides above still win.",
    "  --headless           Run Chromium headless",
    "  --headed             Run Chromium headed (recommended first with Xvfb on servers)",
    "  --poll-interval-ms   Run status polling interval. Default: 2000",
    "  --help               Show this message"
  ].join("\n");
}

function buildConfig(options) {
  const robotId = String(options["robot-id"] || process.env.ROBOT_ID || "").trim();
  const profileSuffix = robotId ? robotId.replace(/[^a-zA-Z0-9_-]+/g, "-") : "default";
  const portalOrigin = normalizePortalOrigin(options["portal-origin"] || process.env.PORTAL_ORIGIN);

  return {
    portalOrigin,
    email: String(options.email || process.env.PORTAL_EMAIL || "").trim(),
    password: String(options.password || process.env.PORTAL_PASSWORD || ""),
    robotId,
    step: String(options.step || process.env.ROBOT_STEP || "start").trim() || "start",
    startUrl: String(options["start-url"] || process.env.ROBOT_START_URL || "").trim(),
    tag: String(options.tag || process.env.ROBOT_TAG || "").trim(),
    params: parseJsonOption(options["params-json"] || process.env.ROBOT_PARAMS_JSON, "params-json"),
    runConfig: parseJsonOption(options["config-json"] || process.env.ROBOT_CONFIG_JSON, "config-json"),
    headless: resolveBoolean(
      options.headless !== undefined ? options.headless : process.env.RUNNER_HEADLESS,
      false
    ),
    pollIntervalMs: resolveInteger(
      options["poll-interval-ms"] || process.env.RUNNER_POLL_INTERVAL_MS,
      2000
    ),
    userDataDir: path.resolve(
      options["user-data-dir"]
        || process.env.RUNNER_USER_DATA_DIR
        || path.join(os.tmpdir(), "scraper-runner", profileSuffix)
    ),
    extensionPath: path.resolve(
      options["extension-path"]
        || process.env.RUNNER_EXTENSION_PATH
        || path.join(__dirname, "..", "Scraper")
    ),
    proxy: buildProxyConfig(options, { portalOrigin }),
    stealthLocale: String(options["stealth-locale"] || process.env.RUNNER_STEALTH_LOCALE || "").trim(),
    stealthTimezone: String(options["stealth-timezone"] || process.env.RUNNER_STEALTH_TIMEZONE || "").trim(),
    autoStealthGeo: resolveBoolean(
      options["auto-stealth-geo"] !== undefined ? options["auto-stealth-geo"] : process.env.RUNNER_AUTO_STEALTH_GEO,
      false
    )
  };
}

function normalizeProxyBypassHost(value) {
  return String(value || "").trim().replace(/^\[|\]$/g, "");
}

function addProxyBypassEntry(entries, seen, value) {
  const entry = normalizeProxyBypassHost(value);
  if (!entry) {
    return;
  }

  const key = entry.toLowerCase();
  if (seen.has(key)) {
    return;
  }

  seen.add(key);
  entries.push(entry);
}

function getPortalProxyBypassHosts(portalOrigin) {
  const hosts = [];

  try {
    const parsed = new URL(portalOrigin);
    const hostname = normalizeProxyBypassHost(parsed.hostname);
    if (hostname) {
      hosts.push(hostname);
    }
  } catch (_error) {
    // Invalid portal origins are normalized elsewhere; keep the fallback hosts.
  }

  hosts.push(...CONTROL_PLANE_PROXY_BYPASS_HOSTS);
  return hosts;
}

function buildProxyBypassList(explicitBypass, portalOrigin) {
  const entries = [];
  const seen = new Set();

  String(explicitBypass || "")
    .split(",")
    .forEach((entry) => addProxyBypassEntry(entries, seen, entry));

  getPortalProxyBypassHosts(portalOrigin)
    .forEach((entry) => addProxyBypassEntry(entries, seen, entry));

  return entries.join(",");
}

function buildProxyConfig(options, { portalOrigin = "" } = {}) {
  const server = String(options["proxy-server"] || process.env.RUNNER_PROXY_SERVER || "").trim();
  if (!server) {
    return null;
  }

  const normalizedServer = /^[a-z][a-z0-9+.-]*:\/\//i.test(server) ? server : `http://${server}`;
  const username = String(options["proxy-username"] || process.env.RUNNER_PROXY_USERNAME || "").trim();
  const password = String(options["proxy-password"] || process.env.RUNNER_PROXY_PASSWORD || "");
  const bypass = buildProxyBypassList(
    options["proxy-bypass"] || process.env.RUNNER_PROXY_BYPASS,
    portalOrigin
  );

  const config = { server: normalizedServer };
  if (username) {
    config.username = username;
  }
  if (password) {
    config.password = password;
  }
  if (bypass) {
    config.bypass = bypass;
  }
  return config;
}

function describeProxy(proxy) {
  if (!proxy || !proxy.server) {
    return "none";
  }
  try {
    const parsed = new URL(proxy.server);
    const auth = proxy.username ? `${proxy.username}:***@` : "";
    return `${parsed.protocol}//${auth}${parsed.host}`;
  } catch (_error) {
    return proxy.username ? `${proxy.username}:***@${proxy.server}` : proxy.server;
  }
}

function computeUnpackedExtensionId(extensionPath) {
  const normalized = path.resolve(extensionPath);
  const hash = crypto.createHash("sha256").update(normalized).digest("hex").slice(0, 32);
  return hash.replace(/[0-9a-f]/g, (c) => String.fromCharCode("a".charCodeAt(0) + parseInt(c, 16)));
}

function seedExtensionPreferences(userDataDir, extensionPath) {
  const extensionId = computeUnpackedExtensionId(extensionPath);
  const defaultDir = path.join(userDataDir, "Default");
  fs.mkdirSync(defaultDir, { recursive: true });
  const prefsPath = path.join(defaultDir, "Preferences");
  let prefs = {};
  try {
    prefs = JSON.parse(fs.readFileSync(prefsPath, "utf8"));
  } catch (_error) {
    prefs = {};
  }
  prefs.extensions = prefs.extensions || {};
  prefs.extensions.ui = prefs.extensions.ui || {};
  prefs.extensions.ui.developer_mode = true;
  prefs.extensions.settings = prefs.extensions.settings || {};
  prefs.extensions.settings[extensionId] = prefs.extensions.settings[extensionId] || {};
  prefs.extensions.settings[extensionId].user_scripts_allowed = true;
  fs.writeFileSync(prefsPath, JSON.stringify(prefs));
  return extensionId;
}

const EXTENSION_FINGERPRINT_FILE = ".scraper-extension-fingerprint";
const CACHED_SCRIPT_DIRS = [
  ["Default", "Service Worker", "ScriptCache"],
  ["Default", "Service Worker", "CacheStorage"],
  ["Default", "Code Cache"]
];
const CACHE_INVALIDATION_FILE_EXTENSIONS = new Set([
  ".js", ".mjs", ".cjs", ".html", ".json", ".css"
]);

function computeExtensionFingerprint(extensionPath) {
  const root = path.resolve(extensionPath);
  const stack = [root];
  let maxMtimeMs = 0;
  let fileCount = 0;

  while (stack.length) {
    const current = stack.pop();
    let entries;
    try {
      entries = fs.readdirSync(current, { withFileTypes: true });
    } catch (_error) {
      continue;
    }
    for (const entry of entries) {
      // Skip hidden / nested deps; we only care about source the extension actually loads.
      if (entry.name === "node_modules" || entry.name.startsWith(".")) {
        continue;
      }
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
        continue;
      }
      const ext = path.extname(entry.name).toLowerCase();
      if (!CACHE_INVALIDATION_FILE_EXTENSIONS.has(ext)) {
        continue;
      }
      try {
        const stat = fs.statSync(full);
        if (stat.mtimeMs > maxMtimeMs) {
          maxMtimeMs = stat.mtimeMs;
        }
        fileCount += 1;
      } catch (_error) {
        // Vanished between readdir and stat — ignore.
      }
    }
  }

  // Include file count so adding/removing a file invalidates even when mtimes
  // happen to coincide (e.g. a checkout that touches no files).
  return `${Math.floor(maxMtimeMs)}:${fileCount}`;
}

function invalidateExtensionScriptCacheIfStale(userDataDir, extensionPath, { logger = console } = {}) {
  const resolvedUserDataDir = path.resolve(userDataDir);
  const fingerprintPath = path.join(resolvedUserDataDir, EXTENSION_FINGERPRINT_FILE);
  const currentFingerprint = computeExtensionFingerprint(extensionPath);

  let storedFingerprint = "";
  try {
    storedFingerprint = fs.readFileSync(fingerprintPath, "utf8").trim();
  } catch (_error) {
    // Missing file → treat as stale (first launch with this profile).
  }

  if (storedFingerprint && storedFingerprint === currentFingerprint) {
    return false;
  }

  for (const segments of CACHED_SCRIPT_DIRS) {
    const dir = path.join(resolvedUserDataDir, ...segments);
    try {
      fs.rmSync(dir, { recursive: true, force: true });
    } catch (error) {
      logger?.warn?.(`Failed to clear Chromium cache dir ${dir}: ${error?.message || error}`);
    }
  }

  try {
    fs.mkdirSync(resolvedUserDataDir, { recursive: true });
    fs.writeFileSync(fingerprintPath, currentFingerprint);
  } catch (error) {
    logger?.warn?.(`Failed to write extension fingerprint to ${fingerprintPath}: ${error?.message || error}`);
  }

  return true;
}

// Probes the proxy's egress IP by issuing an HTTP request through the
// proxy itself. Used by the IP-repetition guard so we can warn when the
// rotating residential provider returns the same exit twice in a row.
// Only HTTP/HTTPS proxies are probed; SOCKS proxies skip the probe and
// the caller proceeds without repeat detection. The locale/timezone that
// ip-api.com returns alongside the IP is intentionally ignored — when
// --auto-stealth-geo is set, cloakbrowser's geoip:true option does its
// own offline mmdb lookup with broader coverage.
async function probeProxyEgress(proxy, { timeoutMs = EGRESS_PROBE_TIMEOUT_MS } = {}) {
  if (!proxy?.server) {
    return null;
  }

  let parsedProxy;
  try {
    parsedProxy = new URL(proxy.server);
  } catch (_err) {
    return null;
  }

  if (parsedProxy.protocol !== "http:" && parsedProxy.protocol !== "https:") {
    return null;
  }

  const headers = {
    Host: EGRESS_PROBE_HOST,
    "User-Agent": "scraper-runner/0.1 (egress-probe)",
    Accept: "application/json",
    Connection: "close"
  };

  if (proxy.username) {
    const auth = Buffer.from(`${proxy.username}:${proxy.password || ""}`).toString("base64");
    headers["Proxy-Authorization"] = `Basic ${auth}`;
  }

  return new Promise((resolve) => {
    const req = http.request({
      host: parsedProxy.hostname,
      port: parsedProxy.port || 80,
      method: "GET",
      path: `http://${EGRESS_PROBE_HOST}${EGRESS_PROBE_PATH}`,
      headers,
      timeout: timeoutMs
    }, (res) => {
      const chunks = [];
      res.on("data", (chunk) => chunks.push(chunk));
      res.on("end", () => {
        try {
          const body = JSON.parse(Buffer.concat(chunks).toString("utf8"));
          if (body && body.status === "success" && body.query) {
            resolve({ ip: String(body.query) });
            return;
          }
        } catch (_err) {
          // Fall through; treat malformed responses as a probe failure.
        }
        resolve(null);
      });
    });
    req.on("error", () => resolve(null));
    req.on("timeout", () => {
      req.destroy();
      resolve(null);
    });
    req.end();
  });
}

function loadEgressHistory(userDataDir) {
  const filePath = path.join(path.resolve(userDataDir), EGRESS_HISTORY_FILE);
  try {
    const parsed = JSON.parse(fs.readFileSync(filePath, "utf8"));
    if (Array.isArray(parsed)) {
      return parsed.filter((entry) => entry && typeof entry.ip === "string");
    }
  } catch (_err) {
    // Missing or corrupt — treat as empty history.
  }
  return [];
}

function recordEgressIp(userDataDir, ip, { now = () => new Date().toISOString() } = {}) {
  const history = loadEgressHistory(userDataDir);
  const empty = { repeated: false, history, recorded: false };
  if (!ip) {
    return empty;
  }

  const repeated = history.some((entry) => entry.ip === ip);
  history.push({ ip, at: now() });
  const trimmed = history.slice(-EGRESS_HISTORY_RING_SIZE);

  const filePath = path.join(path.resolve(userDataDir), EGRESS_HISTORY_FILE);
  try {
    fs.mkdirSync(path.resolve(userDataDir), { recursive: true });
    fs.writeFileSync(filePath, JSON.stringify(trimmed));
  } catch (_err) {
    return { repeated, history: trimmed, recorded: false };
  }

  return { repeated, history: trimmed, recorded: true };
}

function validateConfig(config) {
  const missing = [];

  if (!config.email) missing.push("--email");
  if (!config.password) missing.push("--password");
  if (!config.robotId) missing.push("--robot-id");

  if (missing.length) {
    throw new Error(`Missing required options: ${missing.join(", ")}`);
  }
}

async function waitForServiceWorker(context) {
  const existing = context.serviceWorkers();
  if (existing.length) {
    return existing[0];
  }

  return context.waitForEvent("serviceworker", { timeout: 90_000 });
}

function getExtensionId(serviceWorker) {
  const url = new URL(serviceWorker.url());
  return url.host;
}

async function createBridgePage(context, extensionId) {
  const page = await context.newPage();
  // Receives RUNNER_IMAGES_ALLOWED_CHANGED notifications forwarded by
  // bridge.js. The Playwright route handler installed in
  // installAggressiveResourceBlocker() consults serverImagesAllowed on every
  // image request, so flipping the flag here is sufficient to honor
  // allowServerImages()/blockServerImages() from the IDE script.
  await page.exposeBinding("__scraperRunnerOnImagesAllowedChanged", (_source, allowed) => {
    setServerImagesAllowedFlag(allowed);
  });
  await page.goto(`chrome-extension://${extensionId}/runner/bridge.html`);
  await page.waitForFunction(() => Boolean(globalThis.scraperRunnerBridge));
  return page;
}

async function callBridge(page, method, payload) {
  return page.evaluate(async ({ bridgeMethod, bridgePayload }) => {
    const bridge = globalThis.scraperRunnerBridge;
    if (!bridge || typeof bridge[bridgeMethod] !== "function") {
      throw new Error(`Bridge method is unavailable: ${bridgeMethod}`);
    }

    return bridge[bridgeMethod](bridgePayload);
  }, {
    bridgeMethod: method,
    bridgePayload: payload
  });
}

function createPortalAuthRenewal({
  page,
  credentials,
  intervalMs = PORTAL_AUTH_RENEWAL_INTERVAL_MS,
  retryDelayMs = PORTAL_AUTH_RENEWAL_RETRY_MS,
  callBridgeFn = callBridge,
  setTimeoutFn = setTimeout,
  clearTimeoutFn = clearTimeout,
  logger = console
} = {}) {
  const cleanCredentials = {
    email: String(credentials?.email || "").trim(),
    password: String(credentials?.password || "")
  };
  let stopped = false;
  let renewing = false;
  let timer = null;

  function clearTimer() {
    if (timer) {
      clearTimeoutFn(timer);
      timer = null;
    }
  }

  function schedule(delayMs) {
    if (stopped) {
      return;
    }

    clearTimer();
    const parsedDelay = Number(delayMs);
    const delay = Number.isFinite(parsedDelay) && parsedDelay > 0
      ? Math.floor(parsedDelay)
      : intervalMs;

    timer = setTimeoutFn(() => {
      timer = null;
      return renew();
    }, delay);

    if (timer && typeof timer.unref === "function") {
      timer.unref();
    }
  }

  async function renew() {
    if (stopped || renewing) {
      return null;
    }

    renewing = true;
    try {
      const result = await callBridgeFn(page, "login", cleanCredentials);
      const email = result?.user?.email || cleanCredentials.email;
      if (logger && typeof logger.log === "function") {
        logger.log(`Renewed portal auth for ${email}.`);
      }
      schedule(intervalMs);
      return result;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      if (logger && typeof logger.warn === "function") {
        logger.warn(`Portal auth renewal failed; retrying in ${Math.round(retryDelayMs / 1000)}s: ${message}`);
      }
      schedule(retryDelayMs);
      return null;
    } finally {
      renewing = false;
    }
  }

  if (page && cleanCredentials.email && cleanCredentials.password) {
    schedule(intervalMs);
  }

  return {
    stop() {
      stopped = true;
      clearTimer();
    },
    renewNow: renew,
    isActive() {
      return !stopped && Boolean(page && cleanCredentials.email && cleanCredentials.password);
    }
  };
}

// Per-runner runtime toggle, flipped by allowServerImages()/blockServerImages()
// from the IDE script. Lives at module scope because the runner owns exactly
// one persistent context — there is no per-context fan-out to worry about.
// Stays false until the SW notifies us via the bridge page binding installed
// in createBridgePage().
let serverImagesAllowed = false;

function setServerImagesAllowedFlag(allowed) {
  serverImagesAllowed = Boolean(allowed);
}

function isServerImagesAllowed() {
  return serverImagesAllowed;
}

function shouldBlockRequestForBandwidth(url, resourceType, { imagesAllowed = false } = {}) {
  let parsed;
  try {
    parsed = new URL(url);
  } catch (_err) {
    return false;
  }

  if (RESOURCE_BLOCKER_SCHEME_ALLOWLIST.includes(parsed.protocol)) {
    return false;
  }

  if (BLOCKED_RESOURCE_TYPES.has(resourceType)) {
    if (resourceType === "image" && imagesAllowed) {
      // fall through to the host-pattern check so analytics/ad image beacons
      // can still be blocked even when images are temporarily allowed.
    } else {
      return true;
    }
  }

  const hostname = parsed.hostname.toLowerCase();
  const haystack = `${hostname}${parsed.pathname.toLowerCase()}`;
  return BLOCKED_HOST_PATTERNS.some((pattern) => haystack.includes(pattern));
}

async function installAggressiveResourceBlocker(context) {
  await context.route("**/*", (route, request) => {
    const blocked = shouldBlockRequestForBandwidth(
      request.url(),
      request.resourceType(),
      { imagesAllowed: serverImagesAllowed }
    );
    if (blocked) {
      route.abort().catch(() => { /* request already settled */ });
      return;
    }
    route.continue().catch(() => { /* request already settled */ });
  });
}

function buildStartPayload(config) {
  return {
    robotId: config.robotId,
    runSource: RUN_SOURCE.portalServer,
    ...(config.step ? { step: config.step } : {}),
    ...(config.startUrl ? { url: config.startUrl } : {}),
    ...(config.tag ? { tag: config.tag } : {}),
    ...(config.params ? { params: config.params } : {}),
    ...(config.runConfig ? { config: config.runConfig } : {})
  };
}

function getRunFromState(state, runId) {
  if (!state) {
    return null;
  }

  if (state.selectedRun?.id === runId) {
    return state.selectedRun;
  }

  return Array.isArray(state.runs)
    ? state.runs.find((run) => run.id === runId) || null
    : null;
}

function resolveRobotStartUrl(config, refreshResult) {
  if (config.startUrl) {
    return config.startUrl;
  }

  const robots = Array.isArray(refreshResult?.state?.robots) ? refreshResult.state.robots : [];
  const matchedRobot = robots.find((robot) => String(robot?.id || "").trim() === config.robotId);
  return String(matchedRobot?.url || "").trim();
}

async function humanizePage(page) {
  try {
    const vp = page.viewportSize() || { width: 1280, height: 800 };
    await page.mouse.move(Math.floor(vp.width * 0.3), Math.floor(vp.height * 0.4));
    await page.waitForTimeout(250 + Math.floor(Math.random() * 400));
    await page.mouse.move(Math.floor(vp.width * 0.55), Math.floor(vp.height * 0.6), { steps: 8 });
    await page.waitForTimeout(150 + Math.floor(Math.random() * 250));
    await page.mouse.wheel(0, 120);
  } catch (_error) {
    // Humanization is best-effort; ignore failures.
  }
}

async function waitForRunnablePage(page, {
  timeoutMs = DEFAULT_START_URL_WARMUP_TIMEOUT_MS,
  pollIntervalMs = DEFAULT_START_URL_WARMUP_POLL_INTERVAL_MS,
  reloadAfterMs = DEFAULT_START_URL_WARMUP_RELOAD_AFTER_MS,
  startUrl = ""
} = {}) {
  const deadline = Date.now() + timeoutMs;
  let lastBlockedError = "";
  let lastReloadAt = Date.now();
  let humanized = false;

  for (;;) {
    const pageTitle = await page.title().catch(() => "");
    const pageUrl = typeof page.url === "function" ? page.url() : "";
    const blockedPageError = getBlockedPageError({ pageTitle, pageUrl });

    if (!blockedPageError) {
      return {
        pageTitle,
        pageUrl
      };
    }

    lastBlockedError = blockedPageError;

    if (!humanized) {
      humanized = true;
      await humanizePage(page);
    }

    if (Date.now() >= deadline) {
      throw new Error(`Timed out waiting for the start page to clear. ${lastBlockedError}`);
    }

    if (startUrl && Date.now() - lastReloadAt >= reloadAfterMs) {
      lastReloadAt = Date.now();
      try {
        await page.goto(startUrl, { waitUntil: "domcontentloaded", timeout: 15_000 });
      } catch (_error) {
        // Retry via polling; the next iteration will re-check the page state.
      }
    }

    await page.waitForTimeout(Math.min(pollIntervalMs, Math.max(deadline - Date.now(), 0)));
  }
}

async function warmRobotStartUrl(context, startUrl) {
  if (!startUrl) {
    return null;
  }

  const page = await context.newPage();

  try {
    // Warm the origin with a referer-less visit to the site root when possible,
    // so the actual target request carries realistic cookies/session state.
    try {
      const origin = new URL(startUrl).origin;
      if (origin && origin !== startUrl) {
        await page.goto(origin, { waitUntil: "domcontentloaded", timeout: 15_000 }).catch(() => null);
        await page.waitForTimeout(1_200 + Math.floor(Math.random() * 800));
      }
    } catch (_error) {
      // Ignore URL parsing issues and fall through to the direct navigation.
    }

    await page.goto(startUrl, { waitUntil: "domcontentloaded" });
    return await waitForRunnablePage(page, { startUrl });
  } finally {
    await page.close().catch(() => null);
  }
}

async function monitorRun(page, runId, intervalMs) {
  let previousSummary = "";
  let seenLogCount = 0;

  for (;;) {
    const response = await callBridge(page, "getState");
    const run = getRunFromState(response?.state, runId);

    if (!run) {
      throw new Error(`Run ${runId} is no longer visible in extension state.`);
    }

    if (Array.isArray(run.logs) && run.logs.length > seenLogCount) {
      const nextLogs = run.logs.slice(seenLogCount);
      for (const entry of nextLogs) {
        console.log(entry);  // eslint-disable-line no-console
      }
      seenLogCount = run.logs.length;
    }

    const summary = `[run ${run.id}] status=${run.status} phase=${run.phase} queue=${run.queueLength} rows=${run.rows} emits=${run.emits} failures=${run.failures}`;
    if (summary !== previousSummary) {
      console.log(summary);  // eslint-disable-line no-console
      previousSummary = summary;
    }

    if (run.status !== "RUNNING") {
      return run;
    }

    await page.waitForTimeout(intervalMs);
  }
}

async function run() {
  const options = parseArgs(process.argv.slice(2));
  if (options.help) {
    console.log(usage());  // eslint-disable-line no-console
    return;
  }

  const config = buildConfig(options);
  validateConfig(config);

  let context;
  let authRenewal = null;
  const shutdown = createGracefulShutdownController();
  shutdown.install();

  try {
    const cb = await loadCloakBrowser();

    console.log(`Upstream proxy: ${describeProxy(config.proxy)}`);  // eslint-disable-line no-console

    // Probe the proxy egress IP before launch so we can detect IP
    // repetition against recent runs of this robot. Best-effort; SOCKS
    // proxies and probe timeouts skip the guard silently.
    if (config.proxy) {
      const egressProbe = await probeProxyEgress(config.proxy);
      if (egressProbe) {
        console.log(`Proxy egress IP: ${egressProbe.ip}`);  // eslint-disable-line no-console
        const { repeated } = recordEgressIp(config.userDataDir, egressProbe.ip);
        if (repeated) {
          console.log(`WARNING: proxy egress ${egressProbe.ip} matches a recent prior run for this robot — provider may be returning a repeat IP.`);  // eslint-disable-line no-console
          emitRunnerEvent("PROXY_EGRESS_REPEATED", { ip: egressProbe.ip, robotId: config.robotId });
        }
      } else {
        console.log("Proxy egress probe skipped or failed; IP-repetition guard inactive for this run.");  // eslint-disable-line no-console
      }
    }

    // Resolve stealth identity. Cloakbrowser's geoip:true (when enabled
    // via --auto-stealth-geo) reads the proxy exit IP and fills in any
    // locale/timezone we don't pin explicitly, using an offline GeoLite2
    // database. Without --auto-stealth-geo we fall back to the explicit
    // overrides or the hardcoded module defaults.
    const useGeoip = Boolean(config.autoStealthGeo && config.proxy);
    const explicitLocale = config.stealthLocale || (useGeoip ? "" : STEALTH_LOCALE);
    const explicitTimezone = config.stealthTimezone || (useGeoip ? "" : STEALTH_TIMEZONE);
    console.log(`Stealth identity: geoip=${useGeoip} locale=${explicitLocale || "(from proxy geo)"} timezone=${explicitTimezone || "(from proxy geo)"}`);  // eslint-disable-line no-console

    const seededExtensionId = seedExtensionPreferences(config.userDataDir, config.extensionPath);
    console.log(`Seeded userScripts allow-list for extension ${seededExtensionId}.`);  // eslint-disable-line no-console

    if (invalidateExtensionScriptCacheIfStale(config.userDataDir, config.extensionPath)) {
      console.log(`Cleared stale Chromium script cache for extension ${seededExtensionId}.`);  // eslint-disable-line no-console
    }

    setServerImagesAllowedFlag(false);
    context = await cb.launchPersistentContext({
      userDataDir: config.userDataDir,
      headless: config.headless,
      ...(explicitLocale ? { locale: explicitLocale } : {}),
      ...(explicitTimezone ? { timezone: explicitTimezone } : {}),
      ...(useGeoip ? { geoip: true } : {}),
      // Patches page.click/dblclick/hover/type and page.mouse.* / page.keyboard.*
      // with Bezier-curve cursor trajectories, typing jitter, and humanized
      // scroll/click micro-timings — applied to every page in the context.
      humanize: true,
      ...(config.proxy ? { proxy: config.proxy } : {}),
      args: [
        ...STEALTH_LAUNCH_ARGS,
        `--disable-extensions-except=${config.extensionPath}`,
        `--load-extension=${config.extensionPath}`
      ]
    });
    shutdown.setContext(context);

    await installAggressiveResourceBlocker(context);
    console.log("Aggressive resource blocking installed (images, media, fonts, stylesheets, analytics).");  // eslint-disable-line no-console

    const serviceWorker = await waitForServiceWorker(context);
    const extensionId = getExtensionId(serviceWorker);
    const bridgePage = await createBridgePage(context, extensionId);

    await callBridge(bridgePage, "configurePortal", config.portalOrigin);
    const loginResult = await callBridge(bridgePage, "login", {
      email: config.email,
      password: config.password
    });

    console.log(`Authenticated as ${loginResult.user.email} against ${loginResult.portalOrigin}`);  // eslint-disable-line no-console

    authRenewal = createPortalAuthRenewal({
      page: bridgePage,
      credentials: {
        email: config.email,
        password: config.password
      }
    });

    const refreshResult = await callBridge(bridgePage, "refreshRobots");
    const robotCount = Array.isArray(refreshResult?.state?.robots) ? refreshResult.state.robots.length : 0;
    console.log(`Loaded ${robotCount} robot(s) from the portal.`);  // eslint-disable-line no-console

    const resolvedStartUrl = resolveRobotStartUrl(config, refreshResult);
    if (resolvedStartUrl) {
      console.log(`Priming start URL ${resolvedStartUrl} before starting the run.`);  // eslint-disable-line no-console
      try {
        const warmedPage = await warmRobotStartUrl(context, resolvedStartUrl);
        console.log(`Start URL is runnable at ${warmedPage.pageUrl}.`);  // eslint-disable-line no-console
      } catch (error) {
        console.log(`Start URL warmup did not clear in time: ${error?.message || error}. Handing off to the in-run challenge handler.`);  // eslint-disable-line no-console
      }
    }

    const startResponse = await callBridge(bridgePage, "startRun", buildStartPayload(config));
    const runSummary = startResponse?.run;
    if (!runSummary?.id) {
      throw new Error("The extension did not return a run id.");
    }

    emitRunnerEvent("RUN_STARTED", {
      runId: runSummary.id,
      robotId: runSummary.robotId,
      startedAt: runSummary.startedAt || new Date().toISOString()
    });
    console.log(`Started run ${runSummary.id} for robot ${runSummary.robotId}.`);  // eslint-disable-line no-console

    const finalRun = await monitorRun(bridgePage, runSummary.id, config.pollIntervalMs);
    emitRunnerEvent(
      finalRun.status === "FINISHED"
        ? "RUN_FINISHED"
        : (finalRun.status === "ABORTED" ? "RUN_ABORTED" : "RUN_FAILED"),
      {
        runId: finalRun.id,
        robotId: finalRun.robotId,
        finishedAt: finalRun.finishedAt || null,
        status: finalRun.status
      }
    );
    console.log(JSON.stringify({ ok: true, run: finalRun }, null, 2));  // eslint-disable-line no-console

    if (finalRun.status !== "FINISHED") {
      process.exitCode = 1;
    }
  } finally {
    if (authRenewal) {
      authRenewal.stop();
    }
    await shutdown.closeContext("runner finish");
    shutdown.dispose();
  }
}

if (require.main === module) {
  run().catch((error) => {
    emitRunnerEvent("RUN_ERROR", {
      message: error instanceof Error ? error.message : String(error)
    });
    console.error(error instanceof Error ? error.message : String(error));  // eslint-disable-line no-console
    process.exitCode = 1;
  });
}

module.exports = {
  buildConfig,
  buildProxyConfig,
  buildStartPayload,
  computeExtensionFingerprint,
  computeUnpackedExtensionId,
  createPortalAuthRenewal,
  createGracefulShutdownController,
  describeProxy,
  installAggressiveResourceBlocker,
  invalidateExtensionScriptCacheIfStale,
  isServerImagesAllowed,
  loadEgressHistory,
  recordEgressIp,
  seedExtensionPreferences,
  getRunFromState,
  resolveRobotStartUrl,
  setServerImagesAllowedFlag,
  shouldBlockRequestForBandwidth,
  waitForRunnablePage,
  warmRobotStartUrl,
  PORTAL_AUTH_RENEWAL_INTERVAL_MS,
  PORTAL_AUTH_RENEWAL_RETRY_MS,
  PORTAL_AUTH_TOKEN_TTL_MS,
  STEALTH_LAUNCH_ARGS
};
